module.exports = {
    products: [
        {
            _id:'1',
            name:'Snake Plant',
            category: 'Indoor Plants',
            image: '/images/product-1.jpeg',
            price: 60,
            brand: 'Costa Farms',
            rating: 1,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name:'Snake Plant',
            category: 'Indoor Plants',
            image: '/images/product-1.jpeg',
            price: 60,
            brand: 'Costa Farms',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'3',
            name:'Snake Plant',
            category: 'Indoor Plants',
            image: '/images/product-1.jpeg',
            price: 60,
            brand: 'Costa Farms',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'4',
            name:'Snake Plant',
            category: 'Indoor Plants',
            image: '/images/product-1.jpeg',
            price: 60,
            brand: 'Costa Farms',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'5',
            name:'Snake Plant',
            category: 'Indoor Plants',
            image: '/images/product-1.jpeg',
            price: 60,
            brand: 'Costa Farms',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'6',
            name:'Snake Plant',
            category: 'Indoor Plants',
            image: '/images/product-1.jpeg',
            price: 60,
            brand: 'Costa Farms',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};